apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    role: combined
spec:
  serviceName: elasticsearch
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: combined
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: copy-secrets
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true  
        command: ["/bin/sh","-c","mkdir -p /target/ssl\n cp /source/* /target/\n cp source/ssl/* /target/ssl/\n chmod 777 /target"]
        volumeMounts:
          - name: test
            mountPath: "/source"
          - name: config
            mountPath: "/target"
      containers:
      - name: es-data
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: reg.caspinter.nl/base_elasticsearch:6.2.2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2000m
            memory: 3Gi
          requests:
            cpu: 250m
            memory: 3Gi
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: "main"
        - name: NODE_DATA
          value: "true"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: NUMBER_OF_MASTERS
          value: "2"
        - name: ES_JAVA_OPTS
          value: "-Xms1536m -Xmx1536m"
        - name: NETWORK_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery"
        - name: ES_PLUGINS_INSTALL
          value: "https://s3-ap-southeast-2.amazonaws.com/catapult-public-data/readonlyrest-1.16.17-pre3_es6.2.2.zip,x-pack"
        ports:
        - containerPort: 9200
          name: client
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 120
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: config
          mountPath: /elasticsearch/config
      volumes:
      - name: config
        emptyDir: {} 
      - name: test
        secret:
          secretName: elasticsearch-config
          items:
            - key: elasticsearch.yml
              path: elasticsearch.yml
            - key: readonlyrest.yml
              path: readonlyrest.yml
            - key: jvm.options
              path: jvm.options
            - key: log4j2.properties
              path: log4j2.properties
            - key: keystore.jks
              path: ssl/keystore.jks
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
